!  Author: Mojtaba Abdolkhani
!  Email: mojtababdolkhani@gmail.com
PROGRAM MAIN
IMPLICIT NONE 
INTEGER:: I,J,NI,N,G,dx,dy,IJP, ijq,ijz,ijz1,W,val1,last
INTEGER, allocatable:: ELEMENT(:,:) , ELEMENT1 (:)
INTEGER, allocatable :: SIMPLE1 (:), SIMPLE2(:),element11(:),element00(:),unique(:)
double precision, allocatable :: x(:),y(:)
integer, allocatable :: a12(:),a22(:),a13(:),a33(:)
CHARACTER(len=255)::char1
!---------------------------------------------------------
PRINT*,"PLEASE ENTER THE NAME OF INPUT FILE(max 255 character):"
READ(*,*) char1
PRINT*,"PLEASE INPUT THE DEMENSION OF RVE:"
READ(*,*) N
!---------------------------------------------------------
open(2,file=char1)
allocate(ELEMENT(1:N,1:N))
do j=1,N    
 
READ(2,*) (ELEMENT(I,J) , I=1,N)  

end do

do j=1,N    
 do i=1,n
if (ELEMENT(I,J)/=0 .AND. ELEMENT(I,J)/=1)then
print*,"error: Input file number's must be only 0 and 1"
stop
end if
end do
end do

close(2)
!---------------------------------------------------------
IJP = 0
allocate(ELEMENT1 (n*n))
ELEMENT1 =0
DO J=1,N
    DO I=1,N
        IJP=IJP+1

        ELEMENT1(IJP) = ELEMENT(I,J)
        
    END DO
END DO

!---------------------------------------------------------
IJP = 0
allocate(x(0:(n+1)*(N+1)))
allocate(y(0:(n+1)*(N+1)))
x(0)=0.d0 
y(0)=n
dx=1.d0
dy=1.d0

do i=1,n+1
    do j=1,n+1
         ijp = ijp +1 
         x(ijp)=x(0)+(i-1)*dx 
         y(ijp)=y(0)-(j-1)*dy
        
    end do
end do


!---------------------------------------------------------
open(1,file='output.inp')

write(1,*),'*Heading'
write(1,*),'** Job name: Job-3 Model name: Model-1'
write(1,*),'** Generated by: Abaqus/CAE 6.14-1'
write(1,*),'**'
write(1,*),'** PARTS'
write(1,*),'**'
write(1,*),'*Part, name=Part-1-1'
write(1,*),'*Node'
!---------------------------------------------------------
do ijp = 1,(N+1)*(N+1)
    
    write(1,*)ijp,",",x(ijp),",",y(ijp)
    
end do
!---------------------------------------------------------
write(1,*) "*Element, type=CPE4R"
allocate(SIMPLE1((N+1)**4))
allocate(SIMPLE2((N+1)**4))
allocate(unique((N+1)**4))
ijq=0
g=1
w=1
do j =1,(n)
    do i=1,(n)
         ijq=ijq+1
         if (ELEMENT(I,J)==0.00 ) then
            write(1,*) ijq ,",",ijq+n+j+1,",",ijq+n+j,",",ijq+j-1,",",ijq+j
			SIMPLE1(g)=ijq+j-1
			SIMPLE1(g+1)=ijq+j
			SIMPLE1(g+2)=ijq+n+j
			SIMPLE1(g+3)=ijq+n+j+1
			g=g+4
         end if
         if(ELEMENT(I,J)==1.00 ) then
            write(1,*) ijq ,",",ijq+j-1,",",ijq+j,",",ijq+n+j+1,",",ijq+n+j
            SIMPLE2(w)=ijq+j-1
			SIMPLE2(w+1)=ijq+j
			SIMPLE2(w+2)=ijq+n+j
			SIMPLE2(w+3)=ijq+n+j+1
			w=w+4			
         end if
         
    
    end do
end do

!---------------------------------------------------------
write(1,*),"*Nset, nset=Set-1"

last=0
outer:do i=1 , (w-1)
val1=simple2(i)
do j=1,last
if (unique(j)==val1) then
cycle outer
end if 
end do 
last=last+1 
unique(last)=val1 
end do outer

write(1,*)	(unique(i),",",i=1,last)
!---------------------------------------------------------
write(1,*),"*Elset, elset=Set-1"
allocate(element11(n*n))
j=0
    do ijp =1,n*n
    
        if (ELEMENT1(IJP) ==1) then
		j=j+1
            element11(j)=ijp
        end if
        
        
    end do
write(1,*)	(element11(i),",",i=1,j)
!---------------------------------------------------------
 write(1,*),"*Nset, nset=Set-2"
last=0
outer1:do i=1 , (g-1)
val1=simple1(i)
do j=1,last
if (unique(j)==val1) then
cycle outer1
end if 
end do 
last=last+1 
unique(last)=val1 
end do outer1

write(1,*)	(unique(i),",",i=1,last)
 
!---------------------------------------------------------
write(1,*),"*Elset, elset=Set-2"
allocate(element00(n*n))
j=0
    do ijp =1,n*n
    
        if (ELEMENT1(IJP) ==0) then
		j=j+1
            element00(j)=ijp
        end if
        
        
    end do
write(1,*)	(element00(i),",",i=1,j)  
!---------------------------------------------------------
write(1,*) , "**Section: Section-2"
write(1,*) , "*Solid Section, elset=Set-2, material=Material-2"
write(1,*) , "1.,"
write(1,*) , "**Section: Section-1"
write(1,*) , "*Solid Section, elset=Set-1, material=Material-1"
write(1,*) , "1.,"
write(1,*) ,"*End Part"
write(1,*) ,"** " 
write(1,*) ,"**"
write(1,*) ,"** ASSEMBLY"
write(1,*) ,"**"
write(1,*) ,"*Assembly, name=Assembly"
write(1,*) ,"** " 
write(1,*) ,"*Instance, name=PART-1-1, part=PART-1-1"
write(1,*) , "*End Instance"
write(1,*) , "**"
!---------------------------------------------------------
write(1,*),"*Nset, nset=Set-5, instance=Part-1-1 "
J=n+1
allocate(a12(N+1))
Do i=1,(n+1)
 a12(i)=j*i
End do

write(1,*)	(a12(i),",",i=1,(n+1)) 
!---------------------------------------------------------
write(1,*),"*Elset, elset=Set-5, instance=Part-1-1 "
allocate(a22(N))
J=n
Do i=1,(n)
 a22(i)=j*i
End do

write(1,*)	(a22(i),",",i=1,n) 
!----------------------------------------------------------
write(1,*)," *Elset, elset=_Surf-1_S2, internal, instance=Part-1-1 "
allocate(a13(N))
G=0
j=0
DO i =1,(N)
    IJP=1+G
    IF (ELEMENT1(IJP)==0) THEN
	j=j+1
    a13(j)=IJP     
    END IF
    G=G+N
END DO

write(1,*)	(a13(i),",",i=1,j) 
!-------------------------------------------------------------
write(1,*) "*Elset, elset=_Surf-1_S4, internal, instance=Part-1-1"
allocate(a33(N))
G=0
j=0
DO i =1,(N)
    IJP=1+G
    IF (ELEMENT1(IJP)==1) THEN
	j=j+1
    a33(j)=IJP   
    END IF
    G=G+N
    
END DO
write(1,*)	(a33(i),",",i=1,j)   
!---------------------------------------------------------
write(1,*),'*Surface, type=ELEMENT, name=Surf-1'
write(1,*),'_Surf-1_S2, S2'
write(1,*),'_Surf-1_S4, S4'
write(1,*),'*End Assembly'
write(1,*),'**'
write(1,*),'** MATERIALS'
write(1,*),'** '
write(1,*),'*Material, name=Material-1'
write(1,*),'*Elastic'
write(1,*),'1., 0.3'
write(1,*),'*Material, name=Material-2'
write(1,*),'*Elastic'
write(1,*),'0.0001, 0.3'
write(1,*),'**'
write(1,*),'** BOUNDARY CONDITIONS'
write(1,*),'**'
write(1,*),'** Name: BC-1 Type: Displacement/Rotation'
write(1,*),'*Boundary'
write(1,*),'Set-5, 1, 1'
write(1,*),'Set-5, 2, 2'
write(1,*),'**'
write(1,*),'** STEP: Step-1'
write(1,*),'**'
write(1,*),'*Step, name=Step-1, nlgeom=NO'
write(1,*),'*Static'
write(1,*),'1., 1., 1e-05, 1.'
write(1,*),'**'
write(1,*),'** LOADS'
write(1,*),'**'
write(1,*),'** Name: Load-1   Type: Pressure'
write(1,*),'*Dsload'
write(1,*),'Surf-1, P, -1.'
write(1,*),'**'
write(1,*),'** OUTPUT REQUESTS'
write(1,*),'**'
write(1,*),'*Restart, write, frequency=0'
write(1,*),'**'
write(1,*),'** FIELD OUTPUT: F-Output-1'
write(1,*),'**'
write(1,*),'*Output, field, variable=PRESELECT'
write(1,*),'**'
write(1,*),'** HISTORY OUTPUT: H-Output-1'
write(1,*),'**'
write(1,*),'*Output, history, variable=PRESELECT'
write(1,*),'*End Step'
                                                                                                                              
!--------------------------------------------------------
close(1)
!---------------------------------------------------------
STOP
END 